language: go
go:
  - 1.7.4
env:
  - APP_ENV=test
  - APP_CONF_PATH=../conf
services:
  - redis-server
  - postgresql
addons:
  postgresql: "9.5"
before_install:
  - echo -e "machine github.com\n  login 54de8434f752617a7b939636a48999a1ceb11f78" >> ~/.netrc
install:
  - export PATH=$PATH:$HOME/gopath/bin
#  - psql -c 'ALTER USER postgres WITH SUPERUSER'
#  - psql -c 'create database DB_NAME;' -U postgres
  - go get bitbucket.org/liamstask/goose/cmd/goose
  - goose -path=conf -env=test up
  - curl https://glide.sh/get | sh
  - glide install
  - go get golang.org/x/tools/cmd/cover
script:
  - go test -v -cover $(go list ./... | grep -v /vendor/)

