language: go
branches:
  except:
  - /^scrum\d+$/
go:
  - 1.8
env:
  global:
    - APP_ENV=test
    - APP_CONF_PATH=../conf
services:
  - redis-server
  - postgresql
addons:
  postgresql: "9.5"
before_install:
  - export PATH=$PATH:$HOME/gopath/bin
  - echo -e "machine github.com\n  login 54de8434f752617a7b939636a48999a1ceb11f78" >> ~/.netrc
  - psql -c 'ALTER USER postgres WITH SUPERUSER'
  - psql -U postgres -c 'CREATE DATABASE {|PROJECTNAME|}_test;'
  - psql -U postgres -c "CREATE EXTENSION postgis;" {|PROJECTNAME|}_test
  - go get bitbucket.org/liamstask/goose/cmd/goose
  - goose -path=conf -env=test up
install:
  - go get github.com/Masterminds/glide
  - glide install
script:
  - go test -v -cover $(go list ./... | grep -v /vendor/)
  - curl -s https://54de8434f752617a7b939636a48999a1ceb11f78@raw.githubusercontent.com/gtforge/gett_tools_scripts/master/code_analysis/golang/travis-check/static_analysis_tools.sh | bash
