language: go
branches:
  except:
  - /^scrum\d+$/
go:
  - 1.8.1
  - tip
services:
  - redis-server
  - postgresql
addons:
  postgresql: "9.5"
before_install:
  - export PATH=$PATH:$HOME/gopath/bin
  - echo -e "machine github.com\n  login $BUNDLE_GITHUB__COM" >> ~/.netrc
  - psql -c 'ALTER USER postgres WITH SUPERUSER'
  - psql -U postgres -c 'CREATE DATABASE {|PROJECTNAME|}_test;'
  - psql -U postgres -c "CREATE EXTENSION postgis;" {|PROJECTNAME|}_test
  - go get bitbucket.org/liamstask/goose/cmd/goose
  - goose -path=conf -env=test up
install:
  - go get -v github.com/onsi/ginkgo/ginkgo
  - go get -v github.com/onsi/gomega
  - go get github.com/Masterminds/glide
  - glide install
script:
  - curl -s https://$BUNDLE_GITHUB__COM@raw.githubusercontent.com/gtforge/gett_tools_scripts/master/code_analysis/golang/travis-check/go.test.sh | bash
  - curl -s https://$BUNDLE_GITHUB__COM@raw.githubusercontent.com/gtforge/gett_tools_scripts/master/code_analysis/golang/travis-check/static_analysis_tools.sh | bash
after_success:
    - bash <(curl -s https://codecov.io/bash) -t $CODE_COV_KEY
