dist: trusty
sudo: false

branches:
  except:
  - /^scrum\d+$/

addons:
  postgresql: "9.6"
  apt:
    packages:
    - postgresql-9.6-postgis-2.3

services:
- redis-server
- postgresql
- rabbitmq

language: go
go: [ "1.10" ]
env:
  global:
  - PATH=$PATH:$HOME/gopath/bin

before_install:
- echo "machine github.com login $BUNDLE_GITHUB__COM" > $HOME/.netrc
- echo "machine raw.githubusercontent.com login $BUNDLE_GITHUB__COM" >> $HOME/.netrc
- chmod 600 $HOME/.netrc

install:
- go get github.com/onsi/ginkgo/ginkgo
- go get github.com/onsi/gomega
- go get github.com/gtforge/swan
- go get -u github.com/golang/dep/cmd/dep
- dep ensure -v

before_script:
- psql -c 'ALTER USER postgres WITH SUPERUSER'
- psql -U postgres -c 'CREATE DATABASE {|PROJECTNAME|}_test;'
- psql -U postgres -c "CREATE EXTENSION postgis;" {|PROJECTNAME|}_test

script:
- swan -path=conf -env=test up
- curl -n -s https://raw.githubusercontent.com/gtforge/gett_tools_scripts/master/code_analysis/golang/travis-check/go.test.sh | bash
- curl -n -s https://raw.githubusercontent.com/gtforge/gett_tools_scripts/master/code_analysis/golang/travis-check/static_analysis_tools.sh | bash

after_success:
- bash <(curl -s https://codecov.io/bash) -t ${CODECOV_TOKEN:-"$CODE_COV_KEY"} || echo 'Codecov failed to upload.'
