development:
  host: localhost
  driver: postgres
  open: dbname={|PROJECTNAME|}  sslmode=disable
  user_name:
  password:
  log: true
  database: {|PROJECTNAME|}
  open_pool: 20
  idle_pool: 10
test:
  host: localhost
  driver: postgres
  open: dbname={|PROJECTNAME|}_test  sslmode=disable
  user_name:
  password:
  log: true
  database: {|PROJECTNAME|}_test
  open_pool: 20
  idle_pool: 10
